### PR TITLE
create diy.min.js

### PR DESCRIPTION
**Pull request by jomo**
- removed needless whitespace
- removed needless semicolon
- removed needless `var`

Whitespace is not required before and after `=`.

From the ECMAScript [specs about Rules of Automatic Semicolon Insertion](http://ecma-international.org/ecma-262/5.1/#sec-7.9.1):

> When, as the program is parsed from left to right, the end of the input stream of tokens is encountered and the parser is unable to parse the input token stream as a single complete ECMAScript Program, then a semicolon is automatically inserted at the end of the input stream.

We don't need the `var` keyword because we're not in a function and it is defined in the global space no matter what.

This PR compacts this awesome framework to 10 bytes!

### CODE REVIEW

**Comment by adambutler** [comment]
@jomo Great work... can you also add -

```
 <small>...or just 10 bytes <a href="js/diy.min.js">minified</a></small>
```

after "A modern cross-platform JavaScript library & only 18 bytes"

**Comment by jomo** [comment]
There you go

**Comment by jomo** [comment]
Actually I should probably put it inside the `<p>` tag

**Comment by adambutler** [comment]
@jomo #bada55 :shipit:

**Comment by jomo** [comment]
all done!

**Comment by jomo** [comment]
hmm the link isn't working..

**Comment by jomo** [comment]
Ah, sorry for the wrong filename.

> Rename dig.min.js to div.min.js

:+1: :+1: :+1: :+1: :laughing:

**Comment by stuartpb** [comment]
> We don't need the var keyword because we're not in a function and it is defined in the global space no matter what.

Except that, if all minified scripts are being concatenated together in the presence of a `"use strict";`, this will fail

I think we should accept a 1/3 size increase in diy.min.js for compatibility in this edge case

**Comment by jomo** [comment]
But why would you need any other minified scripts? There is no library that can do things diy.js can't do ;)

**Pull request merged**
